### ISSUE TITLE
redmine 3.3

### ISSUE THREAD

**Issue by burg-md** [pidoco/redmine-pidoco#1]
We tried to use your plugin with redmine 3.3 and have some issues with rake command, after the installation of your plugin.
Could you maybe fix this?

`rake --trace redmine:plugins:migrate && service apache2 reload
(in /usr/share/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- dispatcher
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`require'
/usr/share/redmine/plugins/redmine-pidoco/init.rb:24:in `<top (required)>'
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in`require'
/usr/share/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:146:in`each'
/usr/share/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:21:in`<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in`block in load'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in`load'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in`instrument'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:616:in`block (2 levels) in class:Engine'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in`block in class:Engine'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/1.9.1/tsort.rb:150:in`block in tsort_each'
/usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:210:in`block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:209:in`block in each_strongly_connected_component_from'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in`tsort_each_child'
/usr/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:182:in`block in each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
/usr/lib/ruby/1.9.1/tsort.rb:180:in`each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/initializable.rb:54:in`run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:16:in`<top (required)>'
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in`require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in`load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/application.rb:328:in`require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:248:in`call'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:243:in`each'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:187:in`block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:180:in`invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:207:in`each'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:207:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:186:in`block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:180:in`invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:152:in`invoke_task'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:108:in`each'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:117:in`run_with_threads'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:80:in`block in run'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-11.2.2/lib/rake/application.rb:77:in`run'
/var/lib/gems/1.9.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:19:in`load'
/usr/local/bin/rake:19:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
`

**Comment by tec** [comment]
Hi mmohme,

sorry, this plugin was not yet ported to recent redmine versions.

The specific error that you posted is probably solved by editing init.rb:
Delete the line
`require 'dispatcher'`
and replace 
`Dispatcher.to_prepare do`
with
`ActionDispatch::Callbacks.to_prepare do` 

I haven't tested this fix though and I am afraid you will run into more issues when running this plugin on a recent rails/redmine version
